In [29]:
from copy import deepcopy
import numpy as np

a=[[1,4],
   [1,4], 
   [1,4], 
   [1,4]]
b=[[1,
    3,
    3,
    4,
    5]]
a_arr = np.array(b)
a_arr.shape

(1, 5)

In [30]:
np.max(b)

5

In [31]:
a=np.array(a)
a

array([[1, 4],
       [1, 4],
       [1, 4],
       [1, 4]])

In [32]:
b=np.dot(a.T,a)
b

array([[ 4, 16],
       [16, 64]])

In [51]:
a=[[1,4],
   [3,4], 
   [4,4], 
   [5,4]]
a=np.array(a)
b=np.dot(a.T,a)
si_size = b.shape[0]
shift = np.identity(si_size, dtype=float)*(1e-10)
b = b-shift
np.linalg.inv(b)

array([[ 0.11428571, -0.09285714],
       [-0.09285714,  0.09107143]])

In [52]:
a=[[1,4],
   [3,4], 
   [4,4], 
   [5,4]]
a=np.array(a)
b=np.dot(a.T,a)
np.linalg.inv(b)

array([[ 0.11428571, -0.09285714],
       [-0.09285714,  0.09107143]])